services:
    laravel.test:
        container_name: vpn
        depends_on:
            pgsql:
                condition: service_healthy
            redis:
                condition: service_healthy
            memcached:
                condition: service_healthy
            typesense:
                required: false
                condition: service_healthy
            minio:
                required: false
                condition: service_healthy
            selenium:
                required: false
                condition: service_healthy
            mailpit:
                required: false
                condition: service_started
        networks:
            - nginx
    pgsql:
        image: 'postgres:17.2-alpine'
        profiles:
            - pgsql
    redis:
        image: 'redis:7.4-alpine'
        profiles:
            - redis
    memcached:
        image: 'memcached:1.6-alpine'
        profiles:
            - memcached
    typesense:
        profiles:
            - typesense
    minio:
        profiles:
            - minio
    selenium:
        profiles:
            - selenium
    mailpit:
        profiles:
            - mailpit
networks:
    nginx:
        external: true
