services:
    laravel.test: &laravel
        build:
            context: .
            dockerfile: Dockerfile
            args:
                PHP_VERSION: 8.2
                ALPINE_VERSION: ${ALPINE_VERSION:-3.21}
        image: finagin/vpn:${CONTAINER_VERSION:-latest}
        pull_policy: always
        restart: unless-stopped
        environment:
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        depends_on:
            pgsql:
                condition: service_healthy
            redis:
                condition: service_healthy
            memcached:
                condition: service_healthy
        volumes:
            - 'storage:/var/www/html/storage/app'
        networks:
            - sail
    nginx:
        image: nginx:1.27-alpine${ALPINE_VERSION:-3.21}-slim
        environment:
            NGINX_HOST: '${NGINX_HOST:-_}'
            NGINX_PORT: '${NGINX_PORT:-80}'
        depends_on:
            laravel.test:
                condition: service_started
        volumes:
            - ./resources/nginx.conf:/etc/nginx/templates/default.conf.template
        networks:
            - sail
    pgsql:
        image: postgres:17.4-alpine${ALPINE_VERSION:-3.21}
        restart: unless-stopped
        environment:
            PGPASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - pgsql:/var/lib/postgresql/data
        networks:
            - sail
        healthcheck:
            test: [ CMD, pg_isready, '-q', '-d', '${DB_DATABASE}', '-U', '${DB_USERNAME}' ]
            retries: 3
            timeout: 5s
    redis:
        image: redis:7.4-alpine${ALPINE_VERSION:-3.21}
        restart: unless-stopped
        volumes:
            - redis:/data
        networks:
            - sail
        healthcheck:
            test: [ CMD, redis-cli, ping ]
            retries: 3
            timeout: 5s
    memcached:
        image: memcached:1.6-alpine${ALPINE_VERSION:-3.21}
        ports:
            - '${FORWARD_MEMCACHED_PORT:-11211}:11211'
        networks:
            - sail
        healthcheck:
            test: [CMD, nc, -z, "127.0.0.1", "11211"]
            retries: 3
            timeout: 5s
    init:
        <<: *laravel
        depends_on: []
        entrypoint: [ composer ]
        command: [ install ]
        profiles:
            - init
volumes:
    pgsql:
        driver: local
    redis:
        driver: local
    storage:
        driver: local
networks:
    sail:
        driver: bridge
